Repository wtsi-npg/npg-irods-python, pull requests merged in 2023-03, with the labels that each got.

#78 Feature: ONT metadata updates
  README.md
  scripts/update-ont-metadata
  setup.py
Labels: enhancement

#84 Improvements to initial ONT metadata update script
  scripts/update-ont-metadata
  src/npg_irods/ont.py
  tests/test_ont.py
Labels: documentation, enhancement

#86 Add Actions workflow to build a Docker image
  .github/workflows/build-image.yml
Labels: enhancement

#87 Merge release and Docker build workflows
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
Labels: bug

#88 Fix missing environment variables in release Action
  .github/workflows/create-release.yml
Labels: bug

#89 Fix reference format error on docker push
  .github/workflows/create-release.yml
Labels: bug

#92 Bump ncipollo/release-action from 1.10.0 to 1.12.0
  .github/workflows/create-release.yml
Labels: dependencies

#94 Refactor log configuration
  scripts/check-checksums
  scripts/check-common-metadata
  scripts/check-replicas
  scripts/copy-confirm
  scripts/repair-checksums
  scripts/repair-common-metadata
  scripts/repair-replicas
  scripts/safe-remove-script
  scripts/update-ont-metadata
  src/npg_irods/utilities.py
Labels: enhancement

#93 Fix a typo in logging
  src/npg_irods/utilities.py
Labels: bug

#98 Add script for locating data objects in iRODS
  scripts/locate-data-objects
  setup.py
  src/npg_irods/db/__init__.py
  src/npg_irods/db/mlwh.py
Labels: enhancement

#102 Add --zone CI argument to script requiring it
  scripts/check-checksums
  scripts/check-common-metadata
  scripts/check-consent-withdrawn
  scripts/check-replicas
  scripts/copy-confirm
  scripts/locate-data-objects
  scripts/repair-checksums
  scripts/repair-common-metadata
  scripts/repair-replicas
  scripts/safe-remove-script
  scripts/update-ont-metadata
  scripts/withdraw-consent
  src/npg_irods/cli.py
  src/npg_irods/ont.py
  src/npg_irods/utilities.py
Labels: enhancement

#108 Improve log message content
  scripts/locate-data-objects
  scripts/update-ont-metadata
  src/npg_irods/db/mlwh.py
  src/npg_irods/ont.py
Labels: enhancement
