Repository wtsi-npg/npg-irods-python, pull requests merged in 2024-06, with the labels that each got.

#318 Fix study/sample metadata updates not updating permissions
  pyproject.toml
  src/npg_irods/cli/enhance_secondary_metadata.py
  src/npg_irods/cli/update_secondary_metadata.py
  src/npg_irods/common.py
  src/npg_irods/metadata/lims.py
  src/npg_irods/utilities.py
  tests/conftest.py
  tests/test_common.py
  tests/test_utilities.py
Labels: bug

#322 Fix association of VFC files with related CRAM files
  src/npg_irods/illumina.py
  src/npg_irods/utilities.py
  tests/data/illumina/synthetic/12345/12345#1.vcf
  tests/data/illumina/synthetic/12345/12345#1_human.vcf
  tests/data/illumina/synthetic/12345/12345#1_xahuman.vcf
  tests/data/illumina/synthetic/12345/12345#2.vcf
  tests/data/illumina/synthetic/12345/12345.vcf
  tests/illumina/test_metadata_update.py
Labels: bug

#324 Set ACL zone for study/sample metadata updates
  src/npg_irods/common.py
Labels: bug

#326 Bump partisan from 2.10.0 to 2.10.2
  requirements.txt
Labels: dependencies

#323 Feature: extend barcode collection search
  src/npg_irods/ont.py
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode01/old_rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode01/old_rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode01/old_rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode02/old_rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode02/old_rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode02/old_rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode03/old_rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode03/old_rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode03/old_rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode04/old_rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode04/old_rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcode04/old_rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/barcoding_summary.txt
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/fail/old_rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/nextflow/cmd_flowcell001_experiment_001.txt
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/nextflow/log_flowcell001_experiment_001.txt
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/nextflow/trace_flowcell001_experiment_001.txt
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/qc/base_count.json
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/qc/metrics_report.json
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/report_experiment_001.html
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/sequencing_summary.txt
  tests/data/ont/synthetic/old_rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell201_b4a1fd79/dorado/7.2.13/sup/simplex/normal/default/unclassified/old_rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/fail/rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/nextflow/cmd_flowcell301_experiment_001.txt
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/nextflow/log_flowcell301_experiment_001.txt
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/nextflow/trace_flowcell301_experiment_001.txt
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode01/rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode01/rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode01/rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode02/rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode02/rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode02/rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode03/rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode03/rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode03/rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode04/rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode04/rebasecalled_multiplexed_experiment_001_2.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcode04/rebasecalled_multiplexed_experiment_001_3.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/barcoding_summary.txt
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/pass/unclassified/rebasecalled_multiplexed_experiment_001_1.fastq
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/qc/base_count.json
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/qc/metrics_report.json
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/report_experiment_001.html
  tests/data/ont/synthetic/rebasecalled_multiplexed_experiment_001/20190904_1514_GA10000_flowcell301_08c179cd/dorado/7.2.13/sup/simplex/normal/default/sequencing_summary.txt
  tests/ont/conftest.py
  tests/ont/test_html_reports.py
  tests/ont/test_metadata_update.py
  tests/ont/test_mlwh_queries.py
Labels: enhancement, python
